WARNING:root:Mesaje a nivel WarningS
INFO:root:Mensaje a nivel info
DEBUG:root:Mensaje a nivel debug
ERROR:root:Ocurrion un error en la base de datos
06:24:33 PM: WARNING [logger_base.py:15] mensaje a nivel warning
06:24:33 PM: INFO [logger_base.py:16] mensaje a nivel info
06:24:33 PM: DEBUG [logger_base.py:17] mensaje a nivel debug
06:24:33 PM: ERROR [logger_base.py:18] Ocurrió un error en la base de datos
06:24:33 PM: DEBUG [logger_base.py:19] se realizó la conexión con exito
2021-02-13 18:25:57,166: WARNING [logger_base.py:12 ] Mesaje a nivel WarningS 
2021-02-13 18:25:57,168: INFO [logger_base.py:13 ] Mensaje a nivel info 
2021-02-13 18:25:57,170: DEBUG [logger_base.py:14 ] Mensaje a nivel debug 
2021-02-13 18:25:57,190: ERROR [logger_base.py:15 ] Ocurrion un error en la base de datos 
06: 27: 47: : WARNING [logger_base.py:13 ] Mesaje a nivel WarningS 
06: 27: 47: : INFO [logger_base.py:14 ] Mensaje a nivel info 
06: 27: 47: : DEBUG [logger_base.py:15 ] Mensaje a nivel debug 
06: 27: 47: : ERROR [logger_base.py:16 ] Ocurrion un error en la base de datos 
06: 29: 06: PM : WARNING [logger_base.py:14 ] Mesaje a nivel WarningS 
06: 29: 06: PM : INFO [logger_base.py:15 ] Mensaje a nivel info 
06: 29: 06: PM : DEBUG [logger_base.py:16 ] Mensaje a nivel debug 
06: 29: 06: PM : ERROR [logger_base.py:17 ] Ocurrion un error en la base de datos 
06: 55: 26: PM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
06: 55: 26: PM : INFO [conexion.py:33 ] <connection object at 0x021E2D38; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0> 
07: 04: 53: PM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
07: 04: 53: PM : DEBUG [conexion.py:36 ] Se abrio el cursor con exito: <cursor object at 0x02090928; closed: 0>  
07: 04: 53: PM : INFO [conexion.py:43 ] <cursor object at 0x02090928; closed: 0> 
07: 30: 15: PM : DEBUG [persona.py:40 ] Id Persona: 1 Nombre: juan, Apellido: saravia, Email: je@gmail  
07: 30: 15: PM : DEBUG [persona.py:42 ] Id Persona: None Nombre: Karla, Apellido: Echeverry, Email: ke@gmail.com  
07: 55: 06: PM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
07: 55: 06: PM : DEBUG [conexion.py:36 ] Se abrio el cursor con exito: <cursor object at 0x03B05028; closed: 0>  
07: 55: 06: PM : DEBUG [personaDao.py:11 ] b'SELECT * FROM persona  ORDER BY id_persona' 
07: 55: 06: PM : DEBUG [personaDao.py:22 ] Id Persona: 12 Nombre: carlos, Apellido: lara, Email: clara@email.com  
07: 57: 14: PM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
07: 57: 14: PM : DEBUG [conexion.py:36 ] Se abrio el cursor con exito: <cursor object at 0x039B6028; closed: 0>  
07: 57: 14: PM : DEBUG [personaDao.py:11 ] b'SELECT * FROM persona  ORDER BY id_persona' 
07: 57: 14: PM : DEBUG [personaDao.py:22 ] Id Persona: 12 Nombre: carlos, Apellido: lara, Email: clara@email.com  
07: 57: 14: PM : DEBUG [personaDao.py:23 ] 12 
08: 13: 16: PM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
08: 13: 16: PM : ERROR [conexion.py:39 ] Error al obtener cursor:'NoneType' object has no attribute 'cursor'  
08: 13: 16: PM : ERROR [personaDao.py:36 ] Exepcion al insetar persona: 'NoneType' object has no attribute 'mogrify'  
08: 13: 16: PM : DEBUG [conexion.py:47 ] Se han cerrado los objetos conexion y cursor 
08: 13: 16: PM : DEBUG [personaDao.py:48 ] Registro Insertado:None  
08: 13: 40: PM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
08: 13: 40: PM : DEBUG [conexion.py:36 ] Se abrio el cursor con exito: <cursor object at 0x016F09A8; closed: 0>  
08: 13: 40: PM : DEBUG [personaDao.py:12 ] b'SELECT * FROM persona  ORDER BY id_persona' 
08: 13: 40: PM : DEBUG [conexion.py:47 ] Se han cerrado los objetos conexion y cursor 
08: 13: 40: PM : DEBUG [personaDao.py:44 ] Id Persona: 12 Nombre: carlos, Apellido: lara, Email: clara@email.com  
08: 13: 40: PM : DEBUG [personaDao.py:45 ] 12 
08: 22: 27: PM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
08: 22: 27: PM : ERROR [conexion.py:39 ] Error al obtener cursor:'NoneType' object has no attribute 'cursor'  
08: 22: 27: PM : ERROR [personaDao.py:36 ] Exepcion al insetar persona: 'NoneType' object has no attribute 'mogrify'  
08: 22: 27: PM : DEBUG [conexion.py:47 ] Se han cerrado los objetos conexion y cursor 
08: 22: 27: PM : DEBUG [personaDao.py:48 ] Registro Insertado:None  
08: 25: 56: PM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
08: 25: 56: PM : ERROR [conexion.py:39 ] Error al obtener cursor:'NoneType' object has no attribute 'cursor'  
08: 25: 56: PM : ERROR [personaDao.py:36 ] Exepcion al insetar persona: 'NoneType' object has no attribute 'mogrify'  
08: 25: 56: PM : DEBUG [conexion.py:47 ] Se han cerrado los objetos conexion y cursor 
08: 25: 56: PM : DEBUG [personaDao.py:48 ] Registro Insertado:None  
08: 28: 27: PM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
08: 28: 27: PM : ERROR [conexion.py:39 ] Error al obtener cursor:'NoneType' object has no attribute 'cursor'  
08: 28: 27: PM : ERROR [personaDao.py:36 ] Exepcion al insetar persona: 'NoneType' object has no attribute 'mogrify'  
08: 28: 27: PM : DEBUG [conexion.py:47 ] Se han cerrado los objetos conexion y cursor 
08: 28: 27: PM : DEBUG [personaDao.py:48 ] Registro Insertado:None  
08: 29: 37: PM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
08: 29: 37: PM : ERROR [conexion.py:39 ] Error al obtener cursor:'NoneType' object has no attribute 'cursor'  
08: 29: 37: PM : ERROR [personaDao.py:36 ] Exepcion al insetar persona: 'NoneType' object has no attribute 'mogrify'  
08: 29: 37: PM : DEBUG [conexion.py:47 ] Se han cerrado los objetos conexion y cursor 
08: 29: 37: PM : DEBUG [personaDao.py:48 ] Registro Insertado:None  
08: 32: 04: PM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
08: 32: 04: PM : ERROR [conexion.py:39 ] Error al obtener cursor:'NoneType' object has no attribute 'cursor'  
08: 32: 04: PM : ERROR [personaDao.py:35 ] Excepción al insertar persona:'NoneType' object has no attribute 'mogrify' 
08: 32: 04: PM : DEBUG [conexion.py:47 ] Se han cerrado los objetos conexion y cursor 
08: 32: 04: PM : DEBUG [personaDao.py:47 ] Registro Insertado:None  
08: 35: 20: PM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
08: 35: 20: PM : ERROR [conexion.py:39 ] Error al obtener cursor:'NoneType' object has no attribute 'cursor'  
08: 35: 20: PM : ERROR [personaDao.py:35 ] Excepción al insertar persona:'NoneType' object has no attribute 'mogrify' 
08: 35: 20: PM : DEBUG [conexion.py:47 ] Se han cerrado los objetos conexion y cursor 
08: 35: 20: PM : DEBUG [personaDao.py:47 ] Registro Insertado:None  
08: 37: 53: PM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
08: 37: 53: PM : DEBUG [conexion.py:36 ] Se abrio el cursor con exito: <cursor object at 0x019E19A8; closed: 0>  
08: 37: 53: PM : DEBUG [personaDao.py:12 ] b'SELECT * FROM persona  ORDER BY id_persona' 
08: 37: 53: PM : DEBUG [conexion.py:47 ] Se han cerrado los objetos conexion y cursor 
08: 37: 53: PM : DEBUG [personaDao.py:43 ] Id Persona: 12 Nombre: carlos, Apellido: lara, Email: clara@email.com  
08: 37: 53: PM : DEBUG [personaDao.py:44 ] 12 
08: 39: 16: PM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
08: 39: 16: PM : DEBUG [conexion.py:36 ] Se abrio el cursor con exito: <cursor object at 0x01FA2928; closed: 0>  
08: 39: 16: PM : DEBUG [personaDao.py:12 ] b'SELECT * FROM persona  ORDER BY id_persona' 
08: 39: 16: PM : DEBUG [conexion.py:47 ] Se han cerrado los objetos conexion y cursor 
08: 39: 16: PM : DEBUG [conexion.py:47 ] Se han cerrado los objetos conexion y cursor 
08: 39: 47: PM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
08: 39: 47: PM : ERROR [conexion.py:39 ] Error al obtener cursor:'NoneType' object has no attribute 'cursor'  
08: 39: 47: PM : ERROR [personaDao.py:35 ] Excepción al insertar persona:'NoneType' object has no attribute 'mogrify' 
08: 39: 47: PM : DEBUG [conexion.py:47 ] Se han cerrado los objetos conexion y cursor 
08: 39: 47: PM : DEBUG [personaDao.py:47 ] Registro Insertado:None  
08: 40: 14: PM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
08: 40: 14: PM : ERROR [conexion.py:39 ] Error al obtener cursor:'NoneType' object has no attribute 'cursor'  
08: 40: 14: PM : ERROR [personaDao.py:35 ] Excepción al insertar persona:'NoneType' object has no attribute 'mogrify' 
08: 40: 14: PM : DEBUG [conexion.py:47 ] Se han cerrado los objetos conexion y cursor 
08: 40: 14: PM : DEBUG [personaDao.py:47 ] Registro Insertado:None  
08: 44: 59: PM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
08: 44: 59: PM : ERROR [conexion.py:39 ] Error al obtener cursor:'NoneType' object has no attribute 'cursor'  
08: 44: 59: PM : ERROR [personaDao.py:35 ] Excepción al insertar persona:'NoneType' object has no attribute 'mogrify' 
08: 44: 59: PM : DEBUG [conexion.py:47 ] Se han cerrado los objetos conexion y cursor 
08: 44: 59: PM : DEBUG [personaDao.py:47 ] Registro Insertado:None  
08: 46: 48: PM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
08: 46: 48: PM : ERROR [conexion.py:39 ] Error al obtener cursor:'NoneType' object has no attribute 'cursor'  
08: 46: 48: PM : ERROR [personaDao.py:35 ] Excepción al insertar persona:'NoneType' object has no attribute 'mogrify' 
08: 46: 48: PM : DEBUG [conexion.py:47 ] Se han cerrado los objetos conexion y cursor 
08: 46: 48: PM : DEBUG [personaDao.py:47 ] Personas insertados: None 
10: 51: 08: AM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
10: 51: 08: AM : ERROR [conexion.py:39 ] Error al obtener cursor:'NoneType' object has no attribute 'cursor'  
10: 51: 08: AM : ERROR [personaDao.py:35 ] Excepción al insertar persona:'NoneType' object has no attribute 'mogrify' 
10: 51: 08: AM : DEBUG [conexion.py:47 ] Se han cerrado los objetos conexion y cursor 
10: 51: 08: AM : DEBUG [personaDao.py:47 ] Personas insertados: None 
10: 57: 54: AM : DEBUG [persona.py:40 ] Id Persona: 1 Nombre: juan, Apellido: saravia, Email: je@gmail  
10: 57: 54: AM : DEBUG [persona.py:42 ] Id Persona: None Nombre: Karla, Apellido: Echeverry, Email: ke@gmail.com  
10: 59: 01: AM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
10: 59: 01: AM : ERROR [conexion.py:39 ] Error al obtener cursor:'NoneType' object has no attribute 'cursor'  
10: 59: 01: AM : ERROR [personaDao.py:35 ] Excepción al insertar persona:'NoneType' object has no attribute 'mogrify' 
10: 59: 01: AM : DEBUG [conexion.py:47 ] Se han cerrado los objetos conexion y cursor 
10: 59: 01: AM : DEBUG [personaDao.py:47 ] Personas insertados: None 
11: 00: 27: AM : DEBUG [persona.py:40 ] Id Persona: 1 Nombre: juan, Apellido: saravia, Email: je@gmail  
11: 00: 27: AM : DEBUG [persona.py:42 ] Id Persona: None Nombre: Karla, Apellido: Echeverry, Email: ke@gmail.com  
11: 00: 37: AM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
11: 00: 37: AM : ERROR [personaDao.py:35 ] Excepción al insertar persona:'NoneType' object has no attribute 'mogrify' 
11: 00: 37: AM : DEBUG [conexion.py:47 ] Se han cerrado los objetos conexion y cursor 
11: 00: 37: AM : DEBUG [personaDao.py:47 ] Personas insertados: None 
11: 00: 48: AM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
11: 00: 48: AM : ERROR [personaDao.py:35 ] Excepción al insertar persona:'NoneType' object has no attribute 'mogrify' 
11: 00: 48: AM : DEBUG [conexion.py:47 ] Se han cerrado los objetos conexion y cursor 
11: 00: 48: AM : DEBUG [personaDao.py:47 ] Personas insertados: None 
11: 03: 00: AM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
11: 03: 00: AM : ERROR [personaDao.py:35 ] Excepción al insertar persona:'NoneType' object has no attribute 'mogrify' 
11: 03: 00: AM : DEBUG [conexion.py:50 ] Se han cerrado los objetos conexion y cursor 
11: 03: 00: AM : DEBUG [personaDao.py:47 ] Personas insertados: None 
11: 03: 18: AM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
11: 03: 18: AM : ERROR [conexion.py:39 ] Error al obtener cursor:'NoneType' object has no attribute 'cursor'  
11: 03: 18: AM : ERROR [personaDao.py:35 ] Excepción al insertar persona:'NoneType' object has no attribute 'mogrify' 
11: 03: 18: AM : DEBUG [conexion.py:50 ] Se han cerrado los objetos conexion y cursor 
11: 03: 18: AM : DEBUG [personaDao.py:47 ] Personas insertados: None 
11: 04: 19: AM : DEBUG [conexion.py:24 ] Conexion exitosa: {cls.__conexion}  
11: 04: 19: AM : ERROR [conexion.py:40 ] Error al obtener cursor:'NoneType' object has no attribute 'cursor' 
11: 04: 19: AM : DEBUG [conexion.py:52 ] Se han cerrado los objetos conexion y cursor 
11: 12: 18: AM : DEBUG [conexion.py:24 ] Conexion exitosa: {cls.__conexion}  
11: 12: 18: AM : ERROR [personaDao.py:35 ] Excepción al insertar persona:'psycopg2.extensions.connection' object has no attribute 'obtenerCursor' 
11: 12: 18: AM : DEBUG [conexion.py:52 ] Se han cerrado los objetos conexion y cursor 
11: 12: 18: AM : DEBUG [personaDao.py:47 ] Personas insertados: None 
11: 13: 11: AM : DEBUG [conexion.py:24 ] Conexion exitosa: {cls.__conexion}  
11: 13: 11: AM : ERROR [conexion.py:40 ] Error al obtener cursor:'NoneType' object has no attribute 'cursor' 
11: 13: 11: AM : DEBUG [conexion.py:52 ] Se han cerrado los objetos conexion y cursor 
11: 19: 05: AM : ERROR [conexion.py:26 ] Error al conectar a la BD:  
11: 19: 05: AM : DEBUG [conexion.py:56 ] Se han cerrado los objetos de conexión y cursor 
11: 19: 49: AM : ERROR [conexion.py:26 ] Error al conectar a la BD:  
11: 19: 49: AM : DEBUG [conexion.py:56 ] Se han cerrado los objetos de conexión y cursor 
11: 20: 23: AM : DEBUG [conexion.py:23 ] Conexión exitosa: <connection object at 0x0249BB70; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0> 
11: 20: 23: AM : DEBUG [conexion.py:36 ] Se abrio el cursor con éxito: <cursor object at 0x024529A8; closed: 0> 
11: 20: 23: AM : DEBUG [personaDao.py:27 ] b'INSERT INTO persona(nombre, apelido, email) VALUES(%s,%s,%s)  ' 
11: 20: 23: AM : DEBUG [personaDao.py:28 ] Persona a insertar: Id Persona: None Nombre: Pedro, Apellido: Najera, Email: pnajera@mail.com  
11: 20: 23: AM : ERROR [personaDao.py:35 ] Excepción al insertar persona:no existe la columna «apelido» en la relación «persona»
LINE 1: INSERT INTO persona(nombre, apelido, email) VALUES('Pedro','...
                                    ^
 
11: 20: 23: AM : DEBUG [conexion.py:56 ] Se han cerrado los objetos de conexión y cursor 
11: 20: 23: AM : DEBUG [personaDao.py:47 ] Personas insertados: None 
11: 20: 39: AM : DEBUG [conexion.py:23 ] Conexión exitosa: <connection object at 0x0159EA40; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0> 
11: 20: 39: AM : DEBUG [conexion.py:36 ] Se abrio el cursor con éxito: <cursor object at 0x01552928; closed: 0> 
11: 20: 39: AM : DEBUG [personaDao.py:27 ] b'INSERT INTO persona(nombre, apelido, email) VALUES(%s,%s,%s)  ' 
11: 20: 39: AM : DEBUG [personaDao.py:28 ] Persona a insertar: Id Persona: None Nombre: Pedro, Apellido: Najera, Email: pnajera@mail.com  
11: 20: 39: AM : ERROR [personaDao.py:35 ] Excepción al insertar persona:no existe la columna «apelido» en la relación «persona»
LINE 1: INSERT INTO persona(nombre, apelido, email) VALUES('Pedro','...
                                    ^
 
11: 20: 39: AM : DEBUG [conexion.py:56 ] Se han cerrado los objetos de conexión y cursor 
11: 20: 39: AM : DEBUG [personaDao.py:47 ] Personas insertados: None 
11: 24: 03: AM : DEBUG [conexion.py:23 ] Conexión exitosa: <connection object at 0x01B4BB70; dsn: 'user=postgres password=xxx dbname=test_db host=127.0.0.1 port=5432', closed: 0> 
11: 24: 03: AM : DEBUG [conexion.py:36 ] Se abrio el cursor con éxito: <cursor object at 0x00E529A8; closed: 0> 
11: 24: 03: AM : DEBUG [personaDao.py:27 ] b'INSERT INTO persona(nombre, apellido, email) VALUES(%s,%s,%s)  ' 
11: 24: 03: AM : DEBUG [personaDao.py:28 ] Persona a insertar: Id Persona: None Nombre: Pedro, Apellido: Najera, Email: pnajera@mail.com  
11: 24: 03: AM : DEBUG [conexion.py:56 ] Se han cerrado los objetos de conexión y cursor 
11: 24: 03: AM : DEBUG [personaDao.py:47 ] Personas insertados: 1 
11: 27: 02: AM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
11: 27: 02: AM : ERROR [conexion.py:39 ] Error al obtener cursor:'NoneType' object has no attribute 'cursor' 
11: 27: 02: AM : DEBUG [conexion.py:51 ] Se han cerrado los objetos conexion y cursor 
11: 27: 33: AM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
11: 27: 33: AM : ERROR [conexion.py:39 ] Error al obtener cursor:'NoneType' object has no attribute 'cursor' 
11: 27: 33: AM : DEBUG [conexion.py:51 ] Se han cerrado los objetos conexion y cursor 
11: 31: 52: AM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
11: 31: 52: AM : ERROR [conexion.py:39 ] Error al obtener cursor:'NoneType' object has no attribute 'cursor' 
11: 31: 52: AM : DEBUG [conexion.py:56 ] Se han cerrado los objetos de conexión y cursor 
11: 35: 49: AM : ERROR [conexion.py:26 ] Error al conectar a la BD:  
11: 35: 49: AM : DEBUG [conexion.py:56 ] Se han cerrado los objetos de conexión y cursor 
11: 36: 01: AM : DEBUG [conexion.py:23 ] Conexión exitosa: {cls.__conexion} 
11: 36: 01: AM : DEBUG [conexion.py:36 ] Se abrio el cursor con éxito: <cursor object at 0x01721928; closed: 0> 
11: 36: 01: AM : INFO [conexion.py:59 ] <cursor object at 0x01721928; closed: 0> 
11: 36: 01: AM : DEBUG [conexion.py:56 ] Se han cerrado los objetos de conexión y cursor 
11: 36: 09: AM : DEBUG [conexion.py:23 ] Conexión exitosa: {cls.__conexion} 
11: 36: 09: AM : DEBUG [conexion.py:36 ] Se abrio el cursor con éxito: <cursor object at 0x01CB29A8; closed: 0> 
11: 36: 09: AM : DEBUG [personaDao.py:27 ] b'INSERT INTO persona(nombre, apellido, email) VALUES(%s,%s,%s)  ' 
11: 36: 09: AM : DEBUG [personaDao.py:28 ] Persona a insertar: Id Persona: None Nombre: Juans, Apellido: Acosta, Email: Joder@mail.com  
11: 36: 09: AM : DEBUG [conexion.py:56 ] Se han cerrado los objetos de conexión y cursor 
11: 36: 09: AM : DEBUG [personaDao.py:47 ] Personas insertados: 1 
11: 40: 30: AM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
11: 40: 30: AM : DEBUG [conexion.py:36 ] Se abrio el cursor con éxito: <cursor object at 0x013029A8; closed: 0> 
11: 40: 30: AM : DEBUG [personaDao.py:27 ] b'INSERT INTO persona(nombre, apellido, email) VALUES(%s,%s,%s)  ' 
11: 40: 30: AM : DEBUG [personaDao.py:28 ] Persona a insertar: Id Persona: None Nombre: Juans, Apellido: Acosta, Email: Joder@mail.com  
11: 40: 30: AM : DEBUG [conexion.py:56 ] Se han cerrado los objetos de conexión y cursor 
11: 40: 30: AM : DEBUG [personaDao.py:47 ] Personas insertados: 1 
11: 49: 32: AM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
11: 49: 32: AM : DEBUG [conexion.py:36 ] Se abrio el cursor con éxito: <cursor object at 0x015929A8; closed: 0> 
11: 49: 32: AM : DEBUG [personaDao.py:27 ] b'INSERT INTO persona(nombre, apellido, email) VALUES(%s,%s,%s)  ' 
11: 49: 32: AM : DEBUG [personaDao.py:28 ] Persona a insertar: Id Persona: None Nombre: Juans, Apellido: Acosta, Email: Joder@mail.com  
11: 49: 32: AM : DEBUG [conexion.py:56 ] Se han cerrado los objetos de conexión y cursor 
11: 49: 32: AM : DEBUG [personaDao.py:47 ] Personas insertados: 1 
12: 20: 42: PM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
12: 20: 42: PM : DEBUG [conexion.py:36 ] Se abrio el cursor con éxito: <cursor object at 0x01C539A8; closed: 0> 
12: 20: 42: PM : DEBUG [personaDao.py:45 ] b'UPDATE persona  SET nombre=%s, apellido=%s, email=%s WHERE id_persona=%s ' 
12: 20: 42: PM : DEBUG [personaDao.py:46 ] Persona a actualizar: Id Persona: 15 Nombre: Daniel, Apellido: contreras, Email: dcontreras@gmail.com  
12: 20: 42: PM : DEBUG [conexion.py:56 ] Se han cerrado los objetos de conexión y cursor 
12: 20: 42: PM : DEBUG [personaDao.py:68 ] Personas Actualizadas 1 
12: 24: 39: PM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
12: 24: 39: PM : DEBUG [conexion.py:36 ] Se abrio el cursor con éxito: <cursor object at 0x01174928; closed: 0> 
12: 24: 39: PM : DEBUG [personaDao.py:61 ] b'DELETE FROM persona  WHERE id_persona=%s' 
12: 24: 39: PM : DEBUG [personaDao.py:62 ] Persona a eliminar: Id Persona: 16 Nombre: None, Apellido: None, Email: None  
12: 24: 39: PM : ERROR [personaDao.py:69 ] Excepción al eliminar persona:tuple index out of range 
12: 24: 39: PM : DEBUG [conexion.py:56 ] Se han cerrado los objetos de conexión y cursor 
12: 24: 39: PM : DEBUG [personaDao.py:87 ] Persona eliminada {persona_eliminada} 
12: 25: 32: PM : DEBUG [conexion.py:23 ] Conexion exitosa: {cls.__conexion}  
12: 25: 32: PM : DEBUG [conexion.py:36 ] Se abrio el cursor con éxito: <cursor object at 0x01C04928; closed: 0> 
12: 25: 32: PM : DEBUG [personaDao.py:61 ] b'DELETE FROM persona  WHERE id_persona=%s' 
12: 25: 32: PM : DEBUG [personaDao.py:62 ] Persona a eliminar: Id Persona: 16 Nombre: None, Apellido: None, Email: None  
12: 25: 32: PM : DEBUG [conexion.py:56 ] Se han cerrado los objetos de conexión y cursor 
12: 25: 32: PM : DEBUG [personaDao.py:87 ] Persona eliminada {persona_eliminada} 
